name: 'Create infrastructure for NomStats'

on:
  workflow_dispatch:  # Allows manual trigger from the GitHub Actions UI
  push:
    branches: [main]

env:
  storageAccountName: 'nomstats'

jobs:
  create-resources:
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout Code'
        uses: actions/checkout@v3

      - name: 'Login to Azure using Azure CLI'
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 'Generate HTML files'
        run: python generate_static_website.py

      - name: 'Prepare and Deploy resources'
        run: |
          az storage blob upload-batch -s static_site -d '$web' --account-name $storageAccountName --overwrite